ENH: add an action to search for run IDs using a text query
bokulich-lab/q2-fondue pull request #136
Opened 2022-07-29 09:43 UTC by misialq

Coming soon.

2022-08-18 09:41 UTC, adamovanja requested changes
Thanks for this neatly implemented addition @misialq 🥇.

I added my code comments inline. Could you also add a description of the new action to the ReadMe and maybe also the tutorial?

I tested the new `get-ids-from-query` action with one query [1] and it worked like a charm. Also, fetching metadata for run, bioproject and study IDs still worked as expected [2].
_____
[1] Command tested: `qiime fondue get-ids-from-query --p-email my@mail.com --p-n-jobs 4 --p-query "human gut metagenome[Organism] AND public[Filter] AND (infant OR baby) " --o-ids ids-from-query.qza --verbose`

[2] Tested run ID = `ERR184806`, study ID = `SRP132205` and bioproject ID = `PRJEB16321`

2022-08-18 09:41 UTC, adamovanja commented on q2_fondue/entrezpy_clients/_pipelines.py
> +    for _ids in _chunker(esearch_response.result.uids, BATCH_SIZE):
Could you add a comment here why batching is needed?

2022-08-18 09:41 UTC, adamovanja commented on q2_fondue/entrezpy_clients/_pipelines.py
> +    all_meta = []
here we are recovering run IDs, right? So how about adjusting the variable name `all_meta` to `all_runids` and the comment respectively?

2022-08-18 09:41 UTC, adamovanja commented on q2_fondue/plugin_setup.py
> +    'ids': 'Artifact containing retrieved SRA accession IDs.'
Since this action fetches run accession IDs how about specifying the description accordingly?

2022-08-18 09:41 UTC, adamovanja commented on q2_fondue/plugin_setup.py
> +        'query': 'Search query to retrieve SRA IDs from '
```suggestion
        'query': 'Search query to retrieve SRA run IDs from '
```

2022-08-18 09:41 UTC, adamovanja commented on q2_fondue/plugin_setup.py
> +    name='Find SRA accession IDs based on a search query.',
```suggestion
    name='Find SRA run IDs based on a search query.',
```

2022-08-18 09:41 UTC, adamovanja commented on q2_fondue/plugin_setup.py
> +        'Find SRA accession IDs in the BioSample database '
```suggestion
        'Find SRA run IDs in the BioSample database '
```

2022-08-18 09:41 UTC, adamovanja commented on q2_fondue/plugin_setup.py
> +    'ids': 'Artifact containing retrieved SRA accession IDs.'
```suggestion
    'ids': 'Artifact containing retrieved SRA run IDs.'
```

2022-08-18 14:42 UTC, misialq commented on q2_fondue/entrezpy_clients/_esearch.py
> +    def parse_search_results(self, response, uids: Union[List[str], None]):
When using a text query with ESearch (in contrast to using IDs as input as we have been doing so far) there are no initial IDs to compare ESearch results against - in that case `uids` can be None.

2022-08-19 07:56 UTC, adamovanja approved these changes
thanks for the changes. this looks great to me 🚀

2022-08-19 08:43 UTC, merged