Update QIIME 2 versions in README
bokulich-lab/q2-fondue pull request #150
Opened 2022-12-27 13:47 UTC by lina-kim

I was using `q2-fondue` recently and took the liberty of updating the README:
* Updated installation code to latest QIIME 2 version
* Required v2022.8 instead of v2021.4. The QIIME 2 package channel only contains `q2-fondue` starting in 2022.8, and I believe the QIIME 2 environment version should be the same as that of the package channel. (I could be wrong there - though it seems like good practice in any case.)

2022-12-27 14:31 UTC, adamovanja requested changes
thanks @lina-lim for this update :star:.

As for your 2nd point: Yes, the version of the Q2 environment should match the package channel version. Hence, I suggest we make the following changes to the option 2 installation instructions. Let me know what you think.

2022-12-27 14:31 UTC, adamovanja commented on README.md
> +* Activate the QIIME 2 environment (v2022.8 or higher) and install fondue within:
```suggestion
* Activate the QIIME 2 environment (v2022.8 or higher) and install fondue within while making sure that the used conda channel matches the version of the QIIME 2 environment (replace below `{ENV_VERSION}` with the version number of your QIIME 2 environment):
```

2022-12-27 14:31 UTC, adamovanja commented on README.md
> +conda activate qiime2-2022.11
```suggestion
conda activate qiime2-{ENV_VERSION}
```

2022-12-27 14:31 UTC, adamovanja commented on README.md
> +   -c https://packages.qiime2.org/qiime2/2022.11/tested/ \
```suggestion
   -c https://packages.qiime2.org/qiime2/{ENV_VERSION}/tested/ \
```

2022-12-29 09:56 UTC, lina-kim commented
> thanks @lina-lim for this update ⭐.
> 
> As for your 2nd point: Yes, the version of the Q2 environment should match the package channel version. Hence, I suggest we make the following changes to the option 2 installation instructions. Let me know what you think.

Thanks so much for the suggestions @adamovanja! I agree, and incorporated your suggestions in the latest commit.

2022-12-29 10:30 UTC, adamovanja approved these changes
looks great, thanks @lina-kim

2022-12-29 14:34 UTC, merged